<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

# Create & Access SQLite database using Python

Estimated time needed: **15** minutes

## Objectives

After completing this lab you will be able to:

*   Create a database
*   Create a table
*   Insert data into the table
*   Query data from the table
*   Retrieve the result set into a pandas dataframe
*   Close the database connection

SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine. SQLite is the most widely deployed SQL database engine in the world.

## Task 1: Create database using SQLite

In [11]:
#Install & load sqlite3
#!pip install sqlite3  ##Uncomment the code to install sqlite3
import sqlite3
import pandas as pd

In [12]:
# Connecting to sqlite
# connection object
# conn = sqlite3.connect('INSTRUCTOR.db')

# conn = sqlite3.connect("DRIVER={IBM DB2 ODBC DRIVER};DATABASE=<database_name>;HOSTNAME=<host_name>;PORT=<port_number>;PROTOCOL=TCPIP;UID=<user_name>;PWD=<password>")

%load_ext sql
%sql ibm_db_sa://bgj10144:wWW2Pof88VLdsenI@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb?security=SSL

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Cursor class is an instance using which you can invoke methods that execute SQLite statements, fetch data from the result sets of the queries. You can create Cursor object using the cursor() method of the Connection object/class.

In [13]:
# cursor object
# cursor_obj = conn.cursor()
%sql all_tables << SELECT * FROM syscat.tables where owner = 'BGJ10144'
# cursor_obj
all_tables

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.
Returning data to local variable all_tables

[('BGJ10144', 'SPACEX', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), datetime.datetime(2023, 2, 5, 5, 33, 54, 688304), 10, 4, 62, 101, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 0, 0, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 140, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 13), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'EMPLOYEES', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 488217), datetime.datetime(2023, 2, 12, 13, 53, 30, 626547), datetime.datetime(2023, 2, 12, 13, 53, 30, 626554), datetime.datetime(2023, 2, 12, 14, 7, 49, 368510), 11, 5, 62, 9, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 118, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 488217), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'JOB_HISTORY', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 639458), datetime.datetime(2023, 2, 12, 13, 53, 30, 773963), datetime.datetime(2023, 2, 12, 13, 53, 30, 773970), datetime.datetime(2023, 2, 12, 14, 7, 49, 625896), 4, 6, 62, 9, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 2, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 43, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 639458), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'JOBS', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 788027), datetime.datetime(2023, 2, 12, 13, 53, 30, 932339), datetime.datetime(2023, 2, 12, 13, 53, 30, 932346), datetime.datetime(2023, 2, 12, 14, 7, 49, 879023), 4, 7, 62, 9, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 53, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 788027), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'DEPARTMENTS', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 949382), datetime.datetime(2023, 2, 12, 13, 53, 31, 108259), datetime.datetime(2023, 2, 12, 13, 53, 31, 108266), datetime.datetime(2023, 2, 12, 13, 59, 0, 844035), 4, 8, 62, 2, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 56, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 949382), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'LOCATIONS', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 31, 122712), datetime.datetime(2023, 2, 12, 13, 53, 31, 281695), datetime.datetime(2023, 2, 12, 13, 53, 31, 281703), datetime.datetime(2023, 2, 12, 14, 7, 50, 147171), 2, 9, 62, 2, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 2, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 28, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 31, 122712), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'INSTRUCTOR', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 13, 2, 30, 41, 923861), datetime.datetime(2023, 2, 13, 2, 30, 42, 59806), datetime.datetime(2023, 2, 13, 2, 30, 42, 59812), datetime.datetime(2023, 2, 13, 2, 37, 40, 175704), 5, 10, 62, 3, 1, 0, 1, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 49, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 13, 2, 30, 41, 923861), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 13), ' ', 'N', 'R', 'N', -1.0, None)]

## Task 2: Create a table in the database

In this step we will create a table in the database with following details:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/table.png" align="center">

Before creating a table, let's first if the table already exist or not. To drop the table from a database use **DROP** query. A cursor is an object which helps to execute the query and fetch the records from the database.

In [14]:
# Drop the table if already exists.
# cursor_obj.execute("DROP TABLE IF EXISTS INSTRUCTOR")
%sql DROP TABLE IF EXISTS INSTRUCTOR

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[]

## Dont worry if you get this error:

If you see an exception/error similar to the following, indicating that INSTRUCTOR is an undefined name, that's okay. It just implies that the INSTRUCTOR table does not exist in the table - which would be the case if you had not created it previously.

<strong>Exception: \[IBM]\[CLI Driver]\[DB2/LINUXX8664] SQL0204N  "ABC12345.INSTRUCTOR" is an undefined name.  SQLSTATE=42704 SQLCODE=-204</strong>

In [15]:
# Creating table
# table = """ create table IF NOT EXISTS INSTRUCTOR(ID INTEGER PRIMARY KEY NOT NULL, FNAME VARCHAR(20), LNAME VARCHAR(20), CITY VARCHAR(20), CCODE CHAR(2));"""
 
# cursor_obj.execute(table)
 
#print("Table is Ready")

%sql CREATE TABLE IF NOT EXISTS INSTRUCTOR(ID INTEGER PRIMARY KEY NOT NULL, FNAME VARCHAR(20), LNAME VARCHAR(20), CITY VARCHAR(20), CCODE CHAR(2));

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[]

In [16]:
%sql SELECT * FROM syscat.tables where owner = 'BGJ10144'

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[('BGJ10144', 'SPACEX', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), datetime.datetime(2023, 2, 5, 5, 33, 54, 688304), 10, 4, 62, 101, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 0, 0, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 140, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 5, 5, 22, 24, 305770), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 13), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'EMPLOYEES', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 488217), datetime.datetime(2023, 2, 12, 13, 53, 30, 626547), datetime.datetime(2023, 2, 12, 13, 53, 30, 626554), datetime.datetime(2023, 2, 12, 14, 7, 49, 368510), 11, 5, 62, 9, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 118, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 488217), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'JOB_HISTORY', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 639458), datetime.datetime(2023, 2, 12, 13, 53, 30, 773963), datetime.datetime(2023, 2, 12, 13, 53, 30, 773970), datetime.datetime(2023, 2, 12, 14, 7, 49, 625896), 4, 6, 62, 9, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 2, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 43, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 639458), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'JOBS', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 788027), datetime.datetime(2023, 2, 12, 13, 53, 30, 932339), datetime.datetime(2023, 2, 12, 13, 53, 30, 932346), datetime.datetime(2023, 2, 12, 14, 7, 49, 879023), 4, 7, 62, 9, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 53, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 788027), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'DEPARTMENTS', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 30, 949382), datetime.datetime(2023, 2, 12, 13, 53, 31, 108259), datetime.datetime(2023, 2, 12, 13, 53, 31, 108266), datetime.datetime(2023, 2, 12, 13, 59, 0, 844035), 4, 8, 62, 2, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 56, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 30, 949382), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'LOCATIONS', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 12, 13, 53, 31, 122712), datetime.datetime(2023, 2, 12, 13, 53, 31, 281695), datetime.datetime(2023, 2, 12, 13, 53, 31, 281703), datetime.datetime(2023, 2, 12, 14, 7, 50, 147171), 2, 9, 62, 2, 1, 0, 2, -1, -1, -1, 0, 'BGJ10144SPACE1', None, None, 0, 0, 0, 2, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 28, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2023, 2, 12, 13, 53, 31, 122712), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(2023, 2, 12), ' ', 'N', 'R', 'N', -1.0, None),
 ('BGJ10144', 'INSTRUCTOR', 'BGJ10144', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2023, 2, 13, 3, 50, 18, 269115), datetime.datetime(2023, 2, 13, 3, 50, 18, 359485), datetime.datetime(2023, 2, 13, 3, 50, 18, 359492), None, 5, 10, 62, -1, -1, -1, -1, -1, -1, -1, -1, 'BGJ10144SPACE1', None, None, 0, 0, 0, 1, 1, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, -1, 'N', 999, -1, -1.0, -1, -1.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', -1, datetime.datetime(2023, 2, 13, 3, 50, 18, 269115), 0, ' ', None, None, 'N', 'BGJ10144', ' ', ' ', ' ', datetime.date(1, 1, 1), ' ', 'N', 'R', 'N', -1.0, None)]

## Task 3: Insert data into the table

In this step we will insert some rows of data into the table.

The INSTRUCTOR table we created in the previous step contains 3 rows of data:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/table1.png" align="center">

We will start by inserting just the first row of data, i.e. for instructor Rav Ahuja

In [17]:
# cursor_obj.execute('''insert into INSTRUCTOR values (99, 'TEST', 'TEST2', 'TORONTO', 'CA')''')

%sql INSERT INTO INSTRUCTOR VALUES (1, 'Rav', 'Ahuja', 'TORONTO', 'CA')
%sql SELECT * FROM INSTRUCTOR

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
1 rows affected.
 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[(1, 'Rav', 'Ahuja', 'TORONTO', 'CA')]

The output you will get something as: <strong>sqlite3.Cursor at 0x27a1a491260</strong> which means mySql database has sqlite3.Cursor object at 0x27a1a49126 as output in table. But you may get the different number.

Now use a single query to insert the remaining two rows of data

In [18]:
#cursor_obj.execute('''insert into INSTRUCTOR values (2, 'Raul', 'Chong', 'Markham', 'CA'), (3, 'Hima', 'Vasudevan', 'Chicago', 'US')''')

%sql INSERT INTO INSTRUCTOR VALUES (2, 'Raul', 'Chong', 'Markham', 'CA'), (3, 'Hima', 'Vasudevan', 'Chicago', 'US')

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
2 rows affected.

[]

## Task 4: Query data in the table

In this step we will retrieve data we inserted into the INSTRUCTOR table.

In [19]:
# statement = '''SELECT * FROM INSTRUCTOR'''
# cursor_obj.execute(statement)

# print("All the data")
# output_all = cursor_obj.fetchall()
# for row_all in output_all:
#   print(row_all)

%sql SELECT * FROM INSTRUCTOR

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[(1, 'Rav', 'Ahuja', 'TORONTO', 'CA'),
 (2, 'Raul', 'Chong', 'Markham', 'CA'),
 (3, 'Hima', 'Vasudevan', 'Chicago', 'US')]

In [20]:
## Fetch few rows from the table
# statement = '''SELECT * FROM INSTRUCTOR'''
# cursor_obj.execute(statement)
  
# print("All the data")
# # If you want to fetch few rows from the table we use fetchmany(numberofrows) and mention the number how many rows you want to fetch
# output_many = cursor_obj.fetchmany(2) 
# for row_many in output_many:
#   print(row_many)

In [21]:
# Fetch only FNAME from the table
# statement = '''SELECT FNAME FROM INSTRUCTOR'''
# cursor_obj.execute(statement)
  
# print("All the data")
# output_column = cursor_obj.fetchall()
# for fetch in output_column:
#   print(fetch)

%sql SELECT FNAME FROM INSTRUCTOR

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[('Rav',), ('Raul',), ('Hima',)]

<Strong>Bonus: now write and execute an update statement that changes the Rav's CITY to MOOSETOWN</strong>

In [22]:
# query_update='''update INSTRUCTOR set CITY='MOOSETOWN' where FNAME="Rav"'''
# cursor_obj.execute(query_update)

%sql UPDATE INSTRUCTOR SET CITY='MOOSETOWN' WHERE FNAME='Rav'

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
1 rows affected.

[]

In [23]:
# statement = '''SELECT * FROM INSTRUCTOR'''
# cursor_obj.execute(statement)
  
# print("All the data")
# output1 = cursor_obj.fetchmany(2)
# for row in output1:
#   print(row)

%sql SELECT * FROM INSTRUCTOR

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

[(1, 'Rav', 'Ahuja', 'MOOSETOWN', 'CA'),
 (2, 'Raul', 'Chong', 'Markham', 'CA'),
 (3, 'Hima', 'Vasudevan', 'Chicago', 'US')]

## Task 5: Retrieve data into Pandas

In this step we will retrieve the contents of the INSTRUCTOR table into a Pandas dataframe

In [24]:
import pandas as pd
#retrieve the query results into a pandas dataframe
data = %sql SELECT * FROM INSTRUCTOR
type(data)
#print the dataframe
df = pd.DataFrame(data, columns = data.keys)
df

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb
Done.

   id fname      lname       city ccode
0   1   Rav      Ahuja  MOOSETOWN    CA
1   2  Raul      Chong    Markham    CA
2   3  Hima  Vasudevan    Chicago    US

In [25]:
#print just the LNAME for first row in the pandas data frame
#df.columns
df.lname[0]

'Ahuja'

Once the data is in a Pandas dataframe, you can do the typical pandas operations on it.

For example you can use the shape method to see how many rows and columns are in the dataframe

In [26]:
df.shape

(3, 5)

## Task 6: Close the Connection

We free all resources by closing the connection. Remember that it is always important to close connections so that we can avoid unused connections taking up resources.

In [27]:
# Close the connection
# conn.close()

%sql --disconnect

 * ibm_db_sa://bgj10144:***@fbd88901-ebdb-4a4f-a32e-9822b9fb237b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32731/bludb

## Summary

In this tutorial you created a database & table in Python notebook using SQLite3. Then created a table and insert a few rows of data into it. Then queried the data. You also retrieved the data into a pandas dataframe.

## Author

<a href="https://www.linkedin.com/in/ravahuja/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Rav Ahuja</a>

<a href="https://www.linkedin.com/in/malika-goyal-04798622/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Malika</a>

## Other Contributor(s)

<a href="https://www.linkedin.com/in/lakshmi-holla-b39062149/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Lakshmi Holla</a>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description        |
| ----------------- | ------- | ---------- | ------------------------- |
| 2022-03-03        | 1.0     | Malika     | Created lab using sqlite3 |

<hr>

## <h3 align="center"> © IBM Corporation 2022. All rights reserved. <h3/>